language: node_js
node_js:
  - "node"
script: npm test && npm run integration
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y git xvfb libgtk2.0-0 libxtst6 libxss1 libgconf-2-4 libnss3 libasound2
env:
  - DEBUG=exandria
